name: loft
version: v2.3.2
commands:
  - name: "login"
    usage: "Log into Rancher"
    baseArgs: ["login"]
  - name: "spaces"
    baseArgs: ["list", "spaces"]
    subCommand: "list"
    usage: "List all Loft spaces"
vars:
  - name: RANCHER_TOKEN
    baseArgs: ["vars", "cluster"]
  - name: RANCHER
binaries:
  - os: darwin
    arch: amd64
    path: https://github.com/rancher/cli/releases/download/v2.6.9/rancher-darwin-amd64-v2.6.9.tar.gz
  - os: linux
    arch: amd64
    path: https://github.com/rancher/cli/releases/download/v2.6.9/rancher-linux-amd64-v2.6.9.tar.gz
  - os: windows
    arch: amd64
    path: https://github.com/rancher/cli/releases/download/v2.6.9/rancher-windows-amd64-v2.6.9.zip
  - os: windows
    arch: "386"
    path: https://github.com/rancher/cli/releases/download/v2.6.9/rancher-windows-386-v2.6.9.zip
