name: loft
version: v2.3.2
commands:
  - name: "login"
    usage: "Log into Loft"
    baseArgs: ["login"]
  - name: "spaces"
    baseArgs: ["list", "spaces"]
    subCommand: "list"
    usage: "List all Loft spaces"
vars:
  - name: RANCHER_TOKEN
    baseArgs: ["vars", "cluster"]
  - name: LOFT_USERNAME
    baseArgs: ["vars", "username"]
binaries:
  - os: darwin
    arch: amd64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.3.2/devspace-plugin-loft-darwin-amd64
  - os: darwin
    arch: arm64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.3.2/devspace-plugin-loft-darwin-arm64
  - os: linux
    arch: amd64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.3.2/devspace-plugin-loft-linux-amd64
  - os: linux
    arch: "386"
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.3.2/devspace-plugin-loft-linux-386
  - os: windows
    arch: amd64
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.3.2/devspace-plugin-loft-windows-amd64.exe
  - os: windows
    arch: "386"
    path: https://github.com/loft-sh/devspace-plugin-loft/releases/download/v2.3.2/devspace-plugin-loft-windows-386.exe
